name: flutter_news_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.6.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.2
  pull_to_refresh: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  firebase_messaging: ^16.0.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg:
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700

# -----------------------------
# Flutter Native Splash config
# -----------------------------
flutter_native_splash:
  image: assets/images/splash_icon.png      # Replace with your splash icon
  color: "#FFFFFF"                           # Light theme background
  color_dark: "#000000"                      # Dark theme background
  android: true
  ios: true

  android_12:
    image: assets/images/splash_icon.png
    color: "#FFFFFF"
    color_dark: "#000000"
